### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Model

### ISSUE THREAD

**Issue by Hongyuan-Liu** [AlibabaResearch/efficientteacher#16]
你好，我想用yolov5 v6.1的yolov5s.pt作为预训练模型，通过convert_pt_to_efficient.py转换yolov5s.pt得到e-yolov5s.pt，转换的配置文件用的是configs/sup/public/yolov5s_coco.yaml，转换过程没有报错，于是我用这个e-yolov5s.pt直接采用半监督的方式训练20个类别的模型，但是我在加载e-yolov5s.pt的时候报如下的错误：RuntimeError: Error(s) in loading state_dict for Model:
        size mismatch for head.m.0.weight: copying a param with shape torch.Size([255, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([75, 128, 1, 1]).
        size mismatch for head.m.0.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([75]).
        size mismatch for head.m.1.weight: copying a param with shape torch.Size([255, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([75, 256, 1, 1]).
        size mismatch for head.m.1.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([75]).
        size mismatch for head.m.2.weight: copying a param with shape torch.Size([255, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([75, 512, 1, 1]).
        size mismatch for head.m.2.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([75]).
Traceback (most recent call last):

这是不是意味着，半监督的预训练模型不能直接用官方80个类别的进行训练呢

**Comment by BowieHsu** [comment]
老师您好，您检查一下yaml里面的类别数nc和类别名您修改了吗

**Comment by Hongyuan-Liu** [comment]
我在用convert_pt_to_efficient.py转模型的时候，用的配置文件是configs/sup/public/yolov5s_coco.yaml，这里面没有修改，依然是80个类别，这样转e-yolov5s.pt的过程正常，如果修改configs/sup/public/yolov5s_coco.yaml中的类别是我自己的20，以及类别名称，转换的过程会报错，还是上面的错误。如果configs/sup/public/yolov5s_coco.yaml保持原样，转换得到的e-yolov5s.pt，直接进行半监督训练，在进行半监督训练的时候我参考configs/ssod/custom/yolov5l_custom_ssod.yaml修改了depth_multiple、width_multiple参数，以及我自己的20个类别，并且修改了类别名称，还是报上述的错误。

**Comment by BowieHsu** [comment]
@Hongyuan-Liu 老师您好，我确认一下信息
1.如果您是想用COCO预训练的YOLOv5s来作为初始化权重的话，我们提供了一个已经转好的模型https://github.com/AlibabaResearch/efficientteacher/releases/download/1.0/efficient-yolov5s.pt
2.如果您是想把一个用公版YOLOv5训练出来的，不是80类的模型转换到efficientteacher下面来，可以使用我们的脚本，但是要修改yaml里面的nc和class_name
3.如果您是想用已经转好的pt作为初始化的权重来进行半监督，那么需要修改custom_ssod.yaml下面的weights，把权重加载进去就好了
希望我的回答对您有帮助

**Comment by yjcreation** [comment]
> @Hongyuan-Liu 老师您好，我确认一下信息 1.如果您是想用COCO预训练的YOLOv5s来作为初始化权重的话，我们提供了一个已经转好的模型https://github.com/AlibabaResearch/efficientteacher/releases/download/1.0/efficient-yolov5s.pt 2.如果您是想把一个用公版YOLOv5训练出来的，不是80类的模型转换到efficientteacher下面来，可以使用我们的脚本，但是要修改yaml里面的nc和class_name 3.如果您是想用已经转好的pt作为初始化的权重来进行半监督，那么需要修改custom_ssod.yaml下面的weights，把权重加载进去就好了 希望我的回答对您有帮助

您好！我在真实场景的数据集上操作也遇到同样的问题，该数据集只包含7个类
![image](https://user-images.githubusercontent.com/22938656/223642399-dbb1a22c-92c2-438d-a050-8ad67d18aa56.png)
请问一下我是想用COCO预训练的YOLOv5s或者YOLOv7s来作为初始化权重，在yaml文件中修改了depth_multiple、width_multiple参数，以及7个类别，并且修改了类别名称，为什么自己转化的权重出现这个问题，而使用1中提供则可以正常进行训练了，请问转化的时候有什么区别吗？另外，可以提供YOLOv7s转好的模型吗？  @BowieHsu

**Comment by BowieHsu** [comment]
@yjcreation 我明白您遇到的问题了，我来复现一下，YOLOv7s的模型本周会提供哈

**Comment by BowieHsu** [comment]
@yjcreation 您好，看起来不是数据量太少的问题，感觉是您这里的伪标签生成得太多了，因为在进入半监督训练的时候，伪标签那部分的loss已经大于监督部分的loss了，您可以将teacher_loss_weight调为1，同时关注一下是不是要调整一下ignore_thres_high和nms_iou_thres，还可以把SSOD下面的debug设置为True，观察一下伪标签生成的状况。

**Comment by yjcreation** [comment]
> 您好，看起来不是数据量太少的问题，感觉是您这里的伪标签生成得太多了，因为在进入半监督训练的时候，伪标签那部分的loss已经大于监督部分的loss了，您可以将teacher_loss_weight调为1，同时关注一下是不是要调整一下ignore_thres_high和nms_iou_thres，还可以把SSOD下面的debug设置为True，观察一下伪标签生成的状况。

好的，感谢！通过将teacher_loss_weight调为1，训练看起来正常了。另外请问一下，在验证阶段是不会出现COCO的这个指标显示吗，如下图所示？
![image](https://user-images.githubusercontent.com/22938656/223780093-0a03584e-7e51-4b7d-8940-f6aeed138065.png)
@BowieHsu

**Comment by BowieHsu** [comment]
是的，不会出现COCO验证指标，这个指标需要单独操作生成，可以去查看val.py里面的save_json判断查看具体的逻辑

**Comment by yjcreation** [comment]
> save_json

感谢！请问我在训练过程中突然遇到如下问题：1.如何解决呢？
![image](https://user-images.githubusercontent.com/22938656/223908947-7aa983fc-7264-48f8-92af-47069e33821d.png)
2.在上面提到的训练过程中，采用的是：有标记的图片420多张，无标记的图片4100多张（切分比例10%），由于在半监督阶段出现问题，将teacher_loss_weight调为1。我是加载了在220轮有监督的训练完成后的best.pt，然后yaml文件中的参数设置为
```
epochs: 100
hyp:
  burn_epochs: 20
```
继续开始训练，一且正常，且在日志文件中记录的epoch数为100
![image](https://user-images.githubusercontent.com/22938656/223909786-f57728c9-b3a2-4d24-8117-a1f7891623eb.png)
3.当我使用5%的数据规模的时候，在刚进去半监督的训练时，代码貌似卡住了，停掉代码后，按照2中继续训练的操作，此时出现1中的问题，并且在日志文件中记录的epoch数为316，相当于在我刚才停掉的基础上继续增加了epoch数，不清楚为什么不是和2中一样为100
![image](https://user-images.githubusercontent.com/22938656/223910151-b787fc31-eed3-4535-a7a5-42ff7176d68e.png)
@BowieHsu

**Comment by BowieHsu** [comment]
@yjcreation 您好，我检查一下代码，因为我们的ssod trainer没有尝试过断点重训，这块逻辑有点脆弱。

**Comment by yjcreation** [comment]
> @yjcreation 您好，我检查一下代码，因为我们的ssod trainer没有尝试过断点重训，这块逻辑有点脆弱。

好的，感谢！让我疑惑的是，在上面2中我实际上也是断点重新训练了，但在日志中却直接显示100epoch；而在3中进行同样的操作，却又显示断点重训

**Comment by BowieHsu** [comment]
> 

您好，了解一下细节，3中的实验和2中的实验都是加载同一份权重吗？我现在查下来的状态是3的burn_epochs不为0时，加载出来的模型的初始epoch又不在burn_epochs的范围内，就导致了self.ema错乱掉了

**Comment by yjcreation** [comment]
> > 
> 
> 您好，了解一下细节，3中的实验和2中的实验都是加载同一份权重吗？我现在查下来的状态是3的burn_epochs不为0时，加载出来的模型的初始epoch又不在burn_epochs的范围内，就导致了self.ema错乱掉了

2中的实验是加载的是在真实数据切分为10%下训练的权重best.pt，就是在这里的实验[https://github.com/AlibabaResearch/efficientteacher/issues/16#issuecomment-1460185342](url)，但是我不确定这个best.pt是否在半监督阶段进行了更新，半监督阶段都为0了，应该没有更新。
3中的实验是同样的真实数据切分为5%下训练的权重best.pt，因为刚进入半监督训练的第一轮，程序不知何原因卡住了，GPU利用率一直为0，此时我停掉代码，这个best.pt是在5%的比例下训练得到。
所以两个权重并不是同一份权重。 @BowieHsu

**Comment by BowieHsu** [comment]
@yjcreation 了解了，我们正在重新优化测试ssod_trainer的写法，这需要一点时间，目前可能需要您这边尝试加载coco预训练模型先burn-in一段时间再进入SSOD

**Comment by yjcreation** [comment]
> @yjcreation 了解了，我们正在重新优化测试ssod_trainer的写法，这需要一点时间，目前可能需要您这边尝试加载coco预训练模型先burn-in一段时间再进入SSOD

好的，感谢！您好，刚才我尝试了一下使用代码仓进行有监督的训练，出现以下问题
```
nohup: 忽略输入
EfficientTeacher  2023-3-2 torch 1.11.0 CUDA:0 (NVIDIA GeForce RTX 3090, 24245.8125MB)

[34m[1mtrain_supervised: [0m__immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
Traceback (most recent call last):
  File "/home/cv/.conda/envs/yolox/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/runs_yolov5/exp/weights'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cv/.conda/envs/yolox/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/runs_yolov5/exp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_supervised.py", line 84, in <module>
    main(opt)
  File "train_supervised.py", line 74, in main
    trainer = Trainer(cfg, device, callbacks, LOCAL_RANK, RANK, WORLD_SIZE)
  File "/home/cv/xxx/efficientteacher-main/trainer/trainer.py", line 45, in __init__
    self.set_env(cfg, device, LOCAL_RANK, RANK, WORLD_SIZE, callbacks)
  File "/home/cv/xxx/efficientteacher-main/trainer/trainer.py", line 273, in set_env
    w.mkdir(parents=True, exist_ok=True)  # make dir
  File "/home/cv/.conda/envs/yolox/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/cv/.conda/envs/yolox/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/cv/.conda/envs/yolox/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/runs_yolov5'
```

**Comment by BowieHsu** [comment]
@yjcreation 麻烦将/runs_yolov5改成runs_yolov5，另外您报告的问题我已经复现出来了，正在重新设计几个ema之间的关系
![截屏2023-03-09 下午11 32 59](https://user-images.githubusercontent.com/4092342/224073963-eaca615e-4793-4b9f-9b17-951788be67d2.png)

**Comment by yjcreation** [comment]
> @yjcreation 麻烦将/runs_yolov5改成runs_yolov5，另外您报告的问题我已经复现出来了，正在重新设计几个ema之间的关系 ![截屏2023-03-09 下午11 32 59](https://user-images.githubusercontent.com/4092342/224073963-eaca615e-4793-4b9f-9b17-951788be67d2.png)

感谢！您好，请问一下，如果我想选用yolov7进行实验，在yaml文件修改如下配置
```
# EfficientTeacher by Alibaba Cloud 

# Parameters
project: 'runs_yolov7_5_percent'
adam: False
epochs: 300
weights: 'efficient-yolov7s-simota.pt'
prune_finetune: False
linear_lr: True
hyp:
  lr0: 0.01
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  lrf: 0.1
  scale: 0.9
  no_aug_epochs: 0
  mixup: 0.1
  warmup_epochs: 3

Model:
  depth_multiple: 0.33 # 1.00  # model depth multiple             # 自己还将此处的深度和宽度设置为s的结构
  width_multiple: 0.50 # 1.00  # layer channel multiple
  Backbone: 
    name: 'YoloV7'                      # 
    activation: 'SiLU'
  Neck: 
    name: 'YoloV7' 
    in_channels: [256, 512, 1024]
    out_channels: [256, 512, 1024]
    activation: 'SiLU'
  Head: 
    name: 'YoloV7'
    activation: 'SiLU'
  anchors: [[10,13, 16,30, 33,23],[30,61, 62,45, 59,119],[116,90, 156,198, 373,326]]  # P5/32]
Loss:
  type: 'ComputeLoss'
  cls: 0.3
  obj: 0.7
  anchor_t: 4.0

Dataset:
  data_name: 'coco'
  train: datasets/coco/semi/train2017.1@5.txt # data/custom_train.txt  # 118287 images    # 使用5%的数据进行有监督训练
  val: datasets/coco/val2017.txt # data/custom_val.txt  # 5000 images
  test: datasets/coco/val2017.txt # data/custom_val.txt # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794^
  nc: 7  # number of classes
  np: 0 #number of keypoints
  names: ['gram', 'pseudogra', 'mon', 'gly', 'gloeos', 'clavi', 'anth']    # 自己修改了类名
  img_size: 640
  batch_size: 16    
```
1.请问将Backbone、Neck、Head中分别修改为YoloV7；如果我想加载仓库中提供的权重efficient-yolov7s-simota.pt，Loss部分，我在`/models/loss/loss.py`没有找到SimOTALoss，配置文件中```Loss:
  type: 'ComputeLoss'```这里我应该修改为什么？
2.在Release中，这两个yolov7的权重都是s模型的吗，这两个的区别仅在loss的不同吗？如果想分别使用这两个权重，在配置文件中指定loss的type的时候，应该分别指定什么内容？
![image](https://user-images.githubusercontent.com/22938656/224217387-ca0b9f99-4ad0-43e3-9421-c0bd53f176be.png)
@BowieHsu
